### ISSUE TITLE
switch to discord.js

### ISSUE THREAD

**Issue by ghost** [face-hh/Acolium#2]
eris is not a really good library and hasn't been updated in years, i suggest a discord.js v14 rewrite and eris no logic

**Comment by ghost** [comment]
@face-hh

**Comment by face-hh** [comment]
sure sir yes sir good sir thanks for remidng sir :+1: :1st_place_medal: :drooling_face:

**Comment by ItsZaynMalik** [comment]
nice

**Comment by ItsZaynMalik** [comment]
this is discord.js breh

**Comment by face-hh** [comment]
:joy:

**Comment by ghost** [comment]
discord.js is a good library you and it's well made

**Comment by ghost** [comment]
also it uses only 5kb of ram

**Comment by ItsZaynMalik** [comment]
sheesh kids these days

**Comment by ghost** [comment]
for any bot

**Comment by ItsZaynMalik** [comment]
> discord.js is a good library you and it's well made

thanks i didnt know about it LOL

**Comment by ghost** [comment]
wdym? acolium is already in discord.js???

**Comment by ghost** [comment]
answer please

**Comment by ItsZaynMalik** [comment]
> answer please

no

**Comment by ghost** [comment]
sorry then i thought it was written in eris!

**Comment by ItsZaynMalik** [comment]
OKAYYY

**Comment by face-hh** [comment]
:skull: how do i close issues

**Comment by ghost** [comment]
which one do you prefer? @ItsZaynMalik

**Comment by ItsZaynMalik** [comment]
with help of your hand

> skull how do i close issues

**Comment by ItsZaynMalik** [comment]
> which one do you prefer? @Zayn!

discord.js fr

**Comment by ghost** [comment]
yeah i agree
best lib

**Comment by ghost** [comment]
https://github.com/face-hh/Acolium/blob/e51c9f88c058e21df8220e4f7e82106bc4abb174/package.json#L20 :yawning_face:

**Comment by ItsZaynMalik** [comment]
discord.py is the trash one
discord.js is the best

**Comment by ItsZaynMalik** [comment]
> https://github.com/face-hh/Acolium/blob/e51c9f88c058e21df8220e4f7e82106bc4abb174/package.json#L20

i didnt saw that mb

**Comment by ghost** [comment]
:joy: :+1:

**Comment by ghost** [comment]
sir is this whatsapp?????

**Comment by ItsZaynMalik** [comment]
no this is facebook
and its for uncle's

**Comment by ghost** [comment]
oh ok can you give me pizza recipe

**Comment by ItsZaynMalik** [comment]
https://www.youtube.com/watch?v=kSb62MGJSI4

**Comment by ghost** [comment]
i use 2g internet pls send text

**Comment by ItsZaynMalik** [comment]
i use 1g so i cant send in text

**Comment by ghost** [comment]
@ItsZaynMalik sir can i get your bot source code pls? i want hoest it for myself

**Comment by ItsZaynMalik** [comment]
@Linker-123 Are U Trolling Me
> Enough

**Comment by ghost** [comment]
No not at all!!! SIR pls be kind!!

**Comment by ItsZaynMalik** [comment]
@Linker-123 Ok Enough I Am Bad OK

**Comment by Linker-123** [comment]
:sob: :sob: sir pls be kind

**Comment by ItsZaynMalik** [comment]
> sob sob sir pls be kind

What Is Your DISCORD
